name: docker-publish

on:
  schedule:
    # Run weekly on Sunday at midnight
    - cron: "0 0 * * 0"
  
  # Allow manual trigger
  workflow_dispatch:

  # Run on pushes to main that affect the Dockerfile
  push:
    branches: [ "main" ]
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker-publish.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/shindig-dev:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/shindig-dev:${{ github.sha }}
